# ruff: noqa: F821
"""PyInstaller definition for the Windows-only Broccoli Desktop bundle."""

from pathlib import Path

from PyInstaller.utils.hooks import (
    collect_data_files,
    collect_dynamic_libs,
    collect_submodules,
    copy_metadata,
)

PROJECT_ROOT = Path(SPECPATH).resolve().parent
#: The same file broccoli_desktop.branding hands to the window and the tray, so
#: the executable, its shortcuts, and the running application agree on one logo.
APPLICATION_ICON = PROJECT_ROOT / "broccoli_desktop" / "static" / "images" / "broccoli_icon.ico"
#: Drawn by the bootloader before the interpreter exists, which is the only way
#: to put anything on screen during the seconds this build spends importing
#: pythonnet, PortAudio and numpy and waiting for WebView2. Generated by
#: scripts/build_splash.py and committed, like the icon above; the geometry
#: below is read together with that script's, not independently of it.
SPLASH_IMAGE = PROJECT_ROOT / "broccoli_desktop" / "static" / "images" / "broccoli_splash.png"
RUNTIME_PACKAGES = (
    "webview",
    "pyaudiowpatch",
    "soxr",
    "keyring",
    "pystray",
    "PIL",
)
WINDOWS_RUNTIME_IMPORTS = (
    "webview",
    "webview.guilib",
    "webview.platforms.winforms",
    "webview.platforms.win32",
    "webview.platforms.edgechromium",
    "clr",
    "clr_loader",
    "pyaudiowpatch",
    "_portaudiowpatch",
    "soxr",
    "keyring.backends.Windows",
    "pystray._win32",
    "PIL.Image",
)

# The shell and the interface catalogs are both read from disk at runtime, so
# both have to travel: without the catalogs the first request for the window
# fails on an open() the build itself never performs.
datas = [
    (str(PROJECT_ROOT / "broccoli_desktop" / "static"), "broccoli_desktop/static"),
    (str(PROJECT_ROOT / "broccoli_desktop" / "locales"), "broccoli_desktop/locales"),
]
datas.extend(copy_metadata("keyring"))
binaries = []
# __main__ reaches the runtime through import_module(), whose argument is a
# string PyInstaller cannot follow -- so nothing below __main__ was collected
# and the executable died at startup on every build. Collecting the package
# names them all, which also covers whatever a later dynamic import reaches.
hiddenimports = list(WINDOWS_RUNTIME_IMPORTS) + collect_submodules("broccoli_desktop")
for package in RUNTIME_PACKAGES:
    datas.extend(collect_data_files(package))
    binaries.extend(collect_dynamic_libs(package))

a = Analysis(
    [str(PROJECT_ROOT / "broccoli_desktop" / "__main__.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
splash = Splash(
    str(SPLASH_IMAGE),
    binaries=a.binaries,
    datas=a.datas,
    # The lower-left corner of the text, in image pixels from the top left. It
    # sits on the opaque plate build_splash.py draws at y 236..286, because the
    # text is antialiased against whatever is underneath it and the rest of the
    # image is transparent -- see that script for why that matters.
    text_pos=(28, 268),
    text_size=10,
    # base-content from ui/app.css's dark theme, against the plate's base-200.
    text_color="#e2e5e3",
    # Baked in at build time, so this one line cannot be translated. The first
    # translated step arrives from broccoli_desktop.splash a moment later.
    text_default="Broccoli Desktop",
)
exe = EXE(
    pyz,
    a.scripts,
    splash,
    [],
    exclude_binaries=True,
    name="BroccoliDesktop",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon=str(APPLICATION_ICON),
)
coll = COLLECT(
    exe,
    # Both halves, and this is the one that gets forgotten: EXE embeds the
    # splash resource, COLLECT is what puts Tcl/Tk beside the executable for
    # the bootloader to draw it with. Without it the build still succeeds and
    # no splash ever appears.
    splash.binaries,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="BroccoliDesktop",
)
